blank_issues_enabled: false
contact_links:
  - name: Question / discussion
    url: https://github.com/wavedotso/wave-ui/discussions
    about: For usage questions and ideas, please open a discussion.
